[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox_light.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "none"

[window.padding]
x = 12
y = 12

[font]
size = 16

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"
